name: Generate ASCII artwork

on: 
    push

jobs:
    ascii_job:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: Install cowsay program 
          run: sudo apt-get install cowsay -y
        
        - name: execute cowsay CMD
          run: cowsay -f cat "Meooow , I am a cat" >> cat.txt

        - name: Test if file exists
          run: grep -i "cat" cat.txt

        - name: read file
          run: cat cat.txt

        - name: list repo files
          run: ls -ltra

       